- lib/src/attributes/align_attributes.dart
- lib/src/attributes/index.dart
- lib/src/ui/models/element.dart
- lib/src/ui/models/element_type.dart
- lib/src/ui/widgets/align.dart
- lib/src/ui/widgets/index.dart
- lib/src/ui/widgets/widget_fabric.dart
- lib/src/utils/attribute_parser.dart
Added align widget model and view;
> feat: Align widget

- example/lib/main.dart
- lib/src/duit_impl/host.dart
Added the ability to pass a child widget to DuitHostView for stack display. Added the ability to invert the stack. Added the ability to show a child widget instead of a placeholder; Upd example
> feat: DuitViewHost child widget

- example/lib/main.dart
- lib/flutter_duit.dart
- lib/src/duit_impl/host.dart
- lib/src/duit_impl/view_context.dart
- lib/src/ui/widgets/gesture_detector.dart
- lib/src/utils/gesture_interceptor.dart
- Added gesture interceptor behavior options. 
- Imports updated. 
- Updated example with gestures.
> feat: gesture interceptor behaviors

- lib/src/attributes/index.dart
- lib/src/attributes/lifecycle_state_listener_attributes.dart
- lib/src/ui/models/element.dart
- lib/src/ui/models/element_type.dart
- lib/src/ui/widgets/index.dart
- lib/src/ui/widgets/lifecycle_state_listener.dart
- lib/src/ui/widgets/widget_fabric.dart
- lib/src/utils/attribute_parser.dart
Added a widget that wraps a child subtree and calls specified callbacks when the application lifecycle state changes
> feat: LifecycleStateListener widget

- lib/src/duit_impl/driver.dart
- lib/src/duit_impl/event.dart
Added the ability to perform groups of actions simultaneously and sequentially with a delay
> feat: Event groups

- lib/src/ui/widgets/meta.dart
- lib/src/utils/index.dart
- lib/src/utils/meta_data.dart
Added DuitMetaData inherited widget to reach meta data from context
> feat: DuitMetaData inherited widget

- lib/src/duit_impl/driver.dart
Added .static constructor on DuitDriver for create DuitView from stat…ic json content
> DuitDriver constructor with static content (json)

- lib/src/duit_impl/driver.dart
- lib/src/duit_impl/host.dart
- lib/src/transport/index.dart
- lib/src/transport/native.dart
- lib/src/ui/models/element.dart
- Added the ability to control duit state from native code
- Added `.module` constructor of DuitDriver
- Managed method channels
- Added native transport implementation
> feature: Duit native module

- example/lib/main.dart
- lib/flutter_duit.dart
- lib/src/duit_impl/driver.dart
- lib/src/duit_impl/host.dart
- lib/src/transport/http.dart
- lib/src/transport/ws.dart
- lib/src/ui/models/ui_tree.dart
- lib/src/utils/dev/dev_metrics.dart
- lib/src/utils/dev/index.dart
- lib/src/utils/dev/st_messages.dart
- lib/src/utils/index.dart
Added collection of screen construction time metrics from loading to rendering
> Startup metrics

- lib/src/attributes/index.dart
- lib/src/attributes/intrinsic_height_attributes.dart
- lib/src/ui/models/element.dart
- lib/src/ui/models/element_models.dart
- lib/src/ui/models/element_type.dart
- lib/src/ui/widgets/index.dart
- lib/src/ui/widgets/intrinsic_height.dart
- lib/src/ui/widgets/widget_fabric.dart
Added model and duit widget for IntrinsicHeight widget
> IntrinsicHeight widget

- .github/workflows/run_tests.yaml
- test/flutter_test_config.dart
> ci: CI env variable

- lib/src/animations/animated_props.dart
- lib/src/attributes/text_attrs.dart
- lib/src/ui/widgets/align.dart
- lib/src/ui/widgets/colored_box.dart
- lib/src/ui/widgets/container.dart
- lib/src/ui/widgets/decorated_box.dart
- lib/src/ui/widgets/fitted_box.dart
- lib/src/ui/widgets/image.dart
- lib/src/ui/widgets/opacity.dart
- lib/src/ui/widgets/overflow_box.dart
- lib/src/ui/widgets/padding.dart
- lib/src/ui/widgets/positioned.dart
- lib/src/ui/widgets/radio.dart
- lib/src/ui/widgets/rich_text.dart
- lib/src/ui/widgets/sized_box.dart
- lib/src/ui/widgets/stack.dart
- lib/src/ui/widgets/text.dart
- lib/src/ui/widgets/transform.dart
- lib/src/ui/widgets/wrap.dart
AnimatedAttributes .mergeWithControlle method deprecated, changed deprecated method to .mergeWithAttributes
> fix: text widget unexpected disappear

- lib/flutter_duit.dart
- lib/src/duit_impl/subtree_holder.dart
- lib/src/duit_impl/view_controller_change_listener.dart
- lib/src/utils/detach_extension.dart
- lib/src/utils/index.dart
- pubspec.yaml
Fixed issue with controller dispose when it placed at list and receive new subscriptions when it was be destroyed
> fix: Controller detach and disposing

- example/lib/main.dart
- example/lib/src/custom/example/attributes.dart
- example/lib/src/custom/example/const.dart
- example/lib/src/custom/example/factories.dart
- example/lib/src/custom/example/model.dart
- example/lib/src/custom/example/widget.dart
- example/lib/src/custom/index.dart
- example/pubspec.lock
- example/pubspec.yaml
- lib/src/duit_impl/driver.dart
- lib/src/ui/index.dart
- lib/src/ui/models/element.dart
- lib/src/ui/models/element_models.dart
- lib/src/ui/widgets/widget_fabric.dart
- pubspec.yaml
- Added processing of child views of custom widgets
- Upd example app
> fix: Custom widgets subviews display

- lib/src/animations/animated_prop_helper.dart
- lib/src/animations/index.dart
- lib/src/animations/tween_description.dart
- lib/src/attributes/constrained_box_attributes.dart
- lib/src/attributes/index.dart
- lib/src/ui/models/element.dart
- lib/src/ui/models/element_models.dart
- lib/src/ui/models/element_type.dart
- lib/src/ui/models/type_def.dart
- lib/src/ui/widgets/constrained_box.dart
- lib/src/ui/widgets/index.dart
- lib/src/ui/widgets/widget_fabric.dart
- lib/src/utils/attribute_parser.dart
- lib/src/utils/params_mapper.dart
- test/d_constrained_box_test.dart
- Added ConstrainedBox attributes, model, widget variants
> feat: ConstrainedBox

- lib/src/animations/animation_builder.dart
- lib/src/animations/index.dart
- lib/src/animations/tween.dart
- lib/src/animations/tween_description.dart
- lib/src/animations/tween_helper.dart
- test/d_animations_test.dart
- test/d_on_animation_end_test.dart
- test/d_opacity_test.dart
- Added a class to handle a related group of Tween objects
- Added `TweenHelper ` mixin to simplify `AnimatedBuilder ` code
- Added interval property of type `AnimatedInterval ` for subset of `DuitTweenDescription ` class
> feat: Staggered animations

- lib/src/duit_impl/driver.dart
- lib/src/duit_impl/host.dart
- lib/src/transport/empty.dart
- lib/src/transport/index.dart
- lib/src/ui/models/ui_tree.dart
- lib/src/view_manager/index.dart
- lib/src/view_manager/simple_manager.dart
- lib/src/view_manager/view_layout.dart
- lib/src/view_manager/view_manager.dart
- test/d_host_test.dart
- Added mock transport implementation
- Added ViewManager implementation 
- Clear deprecated API usage
- Change`DuitViewHost ` to work with `UIDriverEvent `
> feat: Top-level layout wrapper

- lib/src/duit_impl/driver.dart
- lib/src/duit_impl/host.dart
- lib/src/view_manager/multiview_layout.dart
- lib/src/view_manager/multiview_manager.dart
- lib/src/view_manager/simple_manager.dart
- lib/src/view_manager/view_layout.dart
- lib/src/view_manager/view_manager.dart
- test/d_component_test.dart
- test/mocks/component_template.dart
- Working with UIElementController has been moved from the driver to ViewManager
- Added tracking of widget display state
> feat: Embedded component

- lib/src/transport/index.dart
- lib/src/transport/ws/index.dart
- lib/src/transport/ws/io.dart
- lib/src/transport/ws/web.dart
- pubspec.yaml
- Added web package to pubspec.yaml 
- Added WASM-compatible WebSocket transport impl
> patch: WASM-compatible WebSocket transport

- lib/src/attributes/index.dart
- lib/src/attributes/intrinsic_width_attributes.dart
- lib/src/ui/models/element.dart
- lib/src/ui/models/element_models.dart
- lib/src/ui/models/element_type.dart
- lib/src/ui/widgets/index.dart
- lib/src/ui/widgets/intrinsic_width.dart
- lib/src/ui/widgets/widget_fabric.dart
- lib/src/utils/attribute_parser.dart
- test/d_intrinsic_width_test.dart
> feat: IntrinsicWidth widget(#76)

- lib/src/attributes/safe_area_attributes.dart
- lib/src/ui/widgets/safe_area.dart
- test/d_container_test.dart
- Added default values when parse SafeArea attributes
- Added test
> patch: SafeArea attributes default values

- example/lib/main.dart
- example/lib/src/theme/custom_token.dart
- example/lib/src/theme/loader.dart
- example/lib/src/theme/override_token.dart
- lib/src/kernel_api/index.dart
- lib/src/view_manager/simple_manager.dart
- Re-export entities from duit_kernel related with theme features
> patch: Export kernel API

- CHANGELOG.md
- example/pubspec.lock
- pubspec.yaml
- test/d_component_test.dart
- test/d_host_test.dart
- test/d_listview_test.dart
- test/mocks/custom.dart
Release v3.3.0 framework version
> v3.3.0 release

- lib/src/attributes/index.dart
- lib/src/attributes/scaffold_attributes.dart
- lib/src/ui/models/element.dart
- lib/src/ui/models/element_models.dart
- lib/src/ui/models/element_type.dart
- lib/src/ui/models/type_def.dart
- lib/src/ui/widgets/app_bar.dart
- lib/src/ui/widgets/index.dart
- lib/src/ui/widgets/scaffold.dart
- lib/src/ui/widgets/widget_fabric.dart
- lib/src/utils/attribute_parser.dart
- lib/src/utils/params_mapper.dart
- test/d_scaffold_test.dart
- test/utils.dart
- Fixed AppBar widget bug by implementing `PreferredSizeWidget`
- Added Scaffold widget
- Added new tests
https://github.com/Duit-Foundation/flutter_duit/issues/87
https://github.com/Duit-Foundation/duit_js/pull/100
https://github.com/Duit-Foundation/duit_go/pull/94
> feat: Scaffold

- lib/src/attributes/index.dart
- lib/src/attributes/inkwell_attributes.dart
- lib/src/duit_impl/host.dart
- lib/src/ui/models/element.dart
- lib/src/ui/models/element_models.dart
- lib/src/ui/models/element_type.dart
- lib/src/ui/models/type_def.dart
- lib/src/ui/widgets/gesture_detector.dart
- lib/src/ui/widgets/index.dart
- lib/src/ui/widgets/inkwell.dart
- lib/src/ui/widgets/widget_fabric.dart
- lib/src/utils/action_utils.dart
- lib/src/utils/attribute_parser.dart
- lib/src/utils/gesture_interceptor.dart
- lib/src/utils/index.dart
- test/d_gesture_detector_test.dart
- test/d_inkwell_test.dart
- test/utils.dart
- Added `InkWell ` widget implementation 
- Added mixin `ActionHandler ` for simplified actions execution in widgets
- Added new tests
- Changed `DuitViewHost.gestureInterceptorBehavior ` default value from `GestureInterceptorBehavior.always` to `GestureInterceptorBehavior.onlyWithAction`
https://github.com/Duit-Foundation/flutter_duit/issues/197
https://github.com/Duit-Foundation/duit_js/pull/101
https://github.com/Duit-Foundation/duit_go/pull/95
> feat: InkWell

- .github/workflows/duit_pr.yaml
- .github/workflows/post_merge.yaml
- lib/src/attributes/carousel_view_attributes.dart
- lib/src/attributes/grid_attributes.dart
- lib/src/attributes/index.dart
- lib/src/ui/models/element.dart
- lib/src/ui/models/element_models.dart
- lib/src/ui/models/element_type.dart
- lib/src/ui/models/type_def.dart
- lib/src/ui/widgets/carouse_view.dart
- lib/src/ui/widgets/grid/grid_base.dart
- lib/src/ui/widgets/grid/grid_builder.dart
- lib/src/ui/widgets/index.dart
- lib/src/ui/widgets/widget_fabric.dart
- lib/src/utils/attribute_parser.dart
- lib/src/utils/params_mapper.dart
- pubspec.yaml
- test/d_carousel_view_test.dart
- test/utils.dart
- Added CarouseView widget implementation 
- Added new tests
- Changed CI workflows (remove Flutter 3.22.x version from matrix)
- Raised minimal Flutter SDK version (till 3.24.x)
https://github.com/Duit-Foundation/flutter_duit/issues/95
https://github.com/Duit-Foundation/duit_go/pull/96
https://github.com/Duit-Foundation/duit_js/pull/102
> feat: CarouseView

- lib/src/utils/params_mapper.dart
Added next decoration modifiers to TextStyle: `TextDecoration`, `TextDecorationStyle`, color and thickness.
> patch: added text decoration attributes to TextStyle

- lib/src/attributes/animated_rotation_attributes.dart
- lib/src/attributes/index.dart
- lib/src/ui/models/element.dart
- lib/src/ui/models/element_models.dart
- lib/src/ui/models/element_type.dart
- lib/src/ui/models/type_def.dart
- lib/src/ui/widgets/animated_rotation.dart
- lib/src/ui/widgets/index.dart
- lib/src/ui/widgets/widget_fabric.dart
- lib/src/utils/attribute_parser.dart
- lib/src/utils/params_mapper.dart
- pubspec.yaml
- test/d_animated_rotation_test.dart
- Added AnimatedRotation widget implementation 
- Added tests
#107 
https://github.com/Duit-Foundation/duit_go/pull/101
https://github.com/Duit-Foundation/duit_js/pull/107
https://github.com/Duit-Foundation/doc_website/pull/10
> feat: AnimatedRotation

- lib/src/attributes/padding_attributes.dart
- lib/src/ui/models/element.dart
- lib/src/ui/models/element_models.dart
- lib/src/ui/models/element_type.dart
- lib/src/ui/models/type_def.dart
- lib/src/ui/widgets/animated_padding.dart
- lib/src/ui/widgets/index.dart
- lib/src/ui/widgets/padding.dart
- lib/src/ui/widgets/widget_fabric.dart
- lib/src/utils/attribute_parser.dart
- test/d_animated_padding_test.dart
- Added AnimatedPadding widget implementation 
- Added test
#101 
https://github.com/Duit-Foundation/duit_go/pull/102
https://github.com/Duit-Foundation/duit_js/pull/108
https://github.com/Duit-Foundation/doc_website/pull/11
> feat: AnimatedPadding

- lib/src/attributes/elevated_button_attributes.dart
- lib/src/attributes/index.dart
- lib/src/ui/widgets/elevated_button.dart
- lib/src/ui/widgets/index.dart
- lib/src/utils/params_mapper.dart
- test/d_button_test.dart
- Added mapping for ButtonStyle
- Added missing props for ElevatedButton attributes
- Update tests for ElevatedButton widget
#266 
https://github.com/Duit-Foundation/duit_js/pull/111
https://github.com/Duit-Foundation/duit_go/pull/105
> patch: added missing props for ElevatedButton attributes

- lib/src/attributes/index.dart
- lib/src/attributes/slivers/custom_scroll_view_attributes.dart
- lib/src/attributes/slivers/index.dart
- lib/src/attributes/slivers/sliver_padding.dart
- lib/src/attributes/slivers/sliver_padding_attributes.dart
- lib/src/attributes/slivers/sliver_props.dart
- lib/src/ui/models/element.dart
- lib/src/ui/models/element_models.dart
- lib/src/ui/models/element_type.dart
- lib/src/ui/models/type_def.dart
- lib/src/ui/widgets/index.dart
- lib/src/ui/widgets/slivers/custom_scroll_view.dart
- lib/src/ui/widgets/slivers/index.dart
- lib/src/ui/widgets/slivers/sliver_padding.dart
- lib/src/ui/widgets/widget_fabric.dart
- lib/src/utils/attribute_parser.dart
- test/d_custom_scroll_view_test.dart
- test/d_sliver_padding_test.dart
- Added CustomScrollView widget implementation 
- Added SliverPadding widget implementation 
- Added tests for both widgets
#169 
#183 
https://github.com/Duit-Foundation/duit_go/pull/107
https://github.com/Duit-Foundation/duit_js/pull/113
> feat: CustomScrollView & SliverPadding

- lib/src/attributes/slivers/index.dart
- lib/src/attributes/slivers/sliver_fill_viewport_attributes.dart
- lib/src/attributes/slivers/sliver_props.dart
- lib/src/ui/models/element.dart
- lib/src/ui/models/element_models.dart
- lib/src/ui/models/element_type.dart
- lib/src/ui/models/type_def.dart
- lib/src/ui/widgets/slivers/index.dart
- lib/src/ui/widgets/slivers/sliver_fill_viewport.dart
- lib/src/ui/widgets/widget_fabric.dart
- lib/src/utils/attribute_parser.dart
- lib/src/utils/child_delegate_builder.dart
- lib/src/utils/index.dart
- test/d_sliver_viewport_test.dart
#175 
https://github.com/Duit-Foundation/duit_js/pull/115
https://github.com/Duit-Foundation/duit_go/pull/110
> feat: SliverFillViewport

- lib/src/ui/models/element.dart
- lib/src/ui/models/element_models.dart
- lib/src/ui/models/element_type.dart
- lib/src/ui/models/type_def.dart
- lib/src/ui/widgets/widget_fabric.dart
- test/d_sliver_to_box_adapter_test.dart
- Added SliverToBoxAdapter widget implementation 
#177 
https://github.com/Duit-Foundation/duit_js/pull/116
https://github.com/Duit-Foundation/duit_go/pull/111
> feat: SliverToBoxAdapter

- lib/src/attributes/index.dart
- lib/src/attributes/offstage_attributes.dart
- lib/src/ui/models/element.dart
- lib/src/ui/models/element_models.dart
- lib/src/ui/models/element_type.dart
- lib/src/ui/widgets/index.dart
- lib/src/ui/widgets/offstage.dart
- lib/src/ui/widgets/widget_fabric.dart
- lib/src/utils/attribute_parser.dart
- test/d_offstage_test.dart
add offstage widget
https://github.com/Duit-Foundation/flutter_duit/issues/86
go - https://github.com/Duit-Foundation/duit_go/pull/112
js - https://github.com/Duit-Foundation/duit_js/pull/117
> feat: Offstage

- lib/src/attributes/slivers/index.dart
- lib/src/attributes/slivers/sliver_opacity_attributes.dart
- lib/src/ui/models/element.dart
- lib/src/ui/models/element_models.dart
- lib/src/ui/models/element_type.dart
- lib/src/ui/models/type_def.dart
- lib/src/ui/widgets/slivers/index.dart
- lib/src/ui/widgets/slivers/sliver_opacity.dart
- lib/src/ui/widgets/widget_fabric.dart
- lib/src/utils/attribute_parser.dart
- test/d_sliver_opacity_test.dart
- Added SliverOpacity widget implementation
- Added tests for SliverOpacity
#178 
- https://github.com/Duit-Foundation/duit_go/pull/114
- https://github.com/Duit-Foundation/duit_js/pull/119
> feat: SliverOpacity

- lib/src/attributes/slivers/index.dart
- lib/src/attributes/slivers/sliver_animated_opacity_attributes.dart
- lib/src/ui/models/element.dart
- lib/src/ui/models/element_models.dart
- lib/src/ui/models/element_type.dart
- lib/src/ui/models/type_def.dart
- lib/src/ui/widgets/slivers/index.dart
- lib/src/ui/widgets/slivers/sliver_animated_opacity.dart
- lib/src/ui/widgets/widget_fabric.dart
- lib/src/utils/attribute_parser.dart
- test/d_sliver_animated_opacity_test.dart
- Added SliverAnimatedOpacity widget implementation 
- Added tests for SliverAnimatedOpacity
#179
- https://github.com/Duit-Foundation/duit_js/pull/120
- https://github.com/Duit-Foundation/duit_go/pull/115/
> feat: SliverAnimatedOpacity

- lib/src/attributes/slivers/index.dart
- lib/src/attributes/slivers/sliver_safe_area_attributes.dart
- lib/src/ui/models/element.dart
- lib/src/ui/models/element_models.dart
- lib/src/ui/models/element_type.dart
- lib/src/ui/models/type_def.dart
- lib/src/ui/widgets/slivers/index.dart
- lib/src/ui/widgets/slivers/sliver_safe_area.dart
- lib/src/ui/widgets/widget_fabric.dart
- lib/src/utils/attribute_parser.dart
- test/d_sliver_safe_area_test.dart
- Added SliverSafeArea widget implementation 
- Added tests
#184 
- https://github.com/Duit-Foundation/duit_go/pull/120
- https://github.com/Duit-Foundation/duit_js/pull/125
> feat: SliverSafeArea

- lib/src/attributes/flexible_space_bar_attributes.dart
- lib/src/attributes/index.dart
- lib/src/attributes/slivers/index.dart
- lib/src/attributes/slivers/sliver_app_bar_attributes.dart
- lib/src/attributes/slivers/sliver_safe_area_attributes.dart
- lib/src/ui/models/element.dart
- lib/src/ui/models/element_models.dart
- lib/src/ui/models/element_type.dart
- lib/src/ui/models/type_def.dart
- lib/src/ui/widgets/flexible_space_bar.dart
- lib/src/ui/widgets/index.dart
- lib/src/ui/widgets/slivers/index.dart
- lib/src/ui/widgets/slivers/sliver_app_bar.dart
- lib/src/ui/widgets/widget_fabric.dart
- lib/src/utils/attribute_parser.dart
- lib/src/utils/params_mapper.dart
- test/d_flexible_space_bar_and_sliver_app_bar_test.dart
- Added SliverAppBar widget implementation 
- Added FlexibleSpaceBar widget implementation 
- Added tests
#176 
- https://github.com/Duit-Foundation/duit_go/pull/124
- https://github.com/Duit-Foundation/duit_js/pull/129
> feat: SliverAppBar & FlexibleSpaceBar

- lib/src/attributes/slivers/index.dart
- lib/src/attributes/slivers/sliver_grid_attributes.dart
- lib/src/ui/models/element.dart
- lib/src/ui/models/element_models.dart
- lib/src/ui/models/element_type.dart
- lib/src/ui/models/type_def.dart
- lib/src/ui/widgets/slivers/index.dart
- lib/src/ui/widgets/slivers/sliver_grid_base.dart
- lib/src/ui/widgets/slivers/sliver_grid_builder.dart
- lib/src/ui/widgets/widget_fabric.dart
- lib/src/utils/attribute_parser.dart
- test/d_sliver_grid_test.dart
- Added SliverGrid widget implementation 
- Added tests
#173 
- https://github.com/Duit-Foundation/duit_go/pull/125
- https://github.com/Duit-Foundation/duit_js/pull/130
> feat: SliverGrid
